name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: sh

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up credentials
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Install dependencies
        run: npm clean-install --omit=dev

      - name: Checkout to production
        run: git checkout -B production

      - name: Update version
        run: |
          echo "${RELEASE_TAG_NAME}" > version
          git add -f version
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}

      - name: Run build
        run: npm run-script build

      - name: Add dist directory
        run: git add -f dist

      - name: Commit files
        run: |
          git commit -m "Release: ${RELEASE_TAG_NAME}" | echo
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}

      # We need to change the tag, so that it points to the newest build.
      # Since that's how we do cache busting on cdn
      - name: Change tag
        run: |
          RELEASE_TITLE=$(gh release view "${RELEASE_TAG_NAME}" --json name --template "{{.name}}")
          RELEASE_DESC=$(gh release view "${RELEASE_TAG_NAME}" --json body --template "{{.body}}")

          git tag -f -a "${RELEASE_TAG_NAME}" -m "$RELEASE_TITLE" -m "$RELEASE_DESC"
        env:
          GITHUB_USER: <ORG>
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}

      - name: Push changes
        run: |
          git push --set-upstream origin production --force
          git push origin "${RELEASE_TAG_NAME}" --force
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
